---
title: "Data Simulation"
author: "Xiangyi Xu"
date: "Thursday, April 09, 2015"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---

####Data simulation is based on article: 
Pastor-Valero, M. (2013). Fruit and vegetable intake and vitamins C and E are associated with a reduced prevalence of cataract in a Spanish Mediterranean population. BMC Ophthalmology, 13:52. 



####Background
Cataract is among the major causes of vision impairment and blindness 
worldwide. Epidemiological studies support the role of antioxidants in the etioloty of cataract, but the evidence of one specific antioxidant over another is inconsistent. Few studies have examined the association of cataract with fruit and vegetable intake with inconclusive results. In this study, the relationship between cataract and fruit and vegetable intake and dietary and blood levels of carotenoids, vitamins C and E were examined in a Spanish Mediterranean population. 



####Data Simulation
The dataset is simulated from the above study. Among 433 elderly with cataract or cataract extraction, 54% are women and 46% are men, their average age iss around 72. The study shows that increasing quartiles  `(13~83, 83~107, 107~143, 143~408 mg/d)` of dietary intakes from `107mg/d` of vitamin C indicating a significant decreasing association with prevalence of cataract or cataract extraction. In the simulated dataset, with enough data, it will show that both age and intake of vitamin C matter much in having cataract or not. Noise such as zodiac signs are added in the study too. 
Hint: log of VitaminC for the analysis of data



####Features
Feature1: age    
Feature2: obesity- Y, N     
Feature3: sex- M, F     
Feature4: marital_status- Y, N     
Feature5: diabetes- Y, N    
Feature6: smoking- Never, Past, Current    
Feature7: VitaminC     
Feature8: zodiac signs     
Outcome:  cataract Y, N      



####Manipulate function is used to generate coefficients.

library(manipulate)
manipulate(with(df,{  
score <- 0.73 + 2^a*(age - 72) - 2^b*log(VitaminC)
prob <- logistic(score)
hist(prob, breaks=50)
}), a=slider(-9, 9, step=0.1, initial = 0), b=slider(-9, 9, step=0.1, initial = 0))



####generate dataset


```{r}

generate_dataset <- function(N=100){
        
        age <- runif(N, min=72-10, max=72+10)
        
        obesity <- sample(c("Y", "N"), N, replace=TRUE, prob=c(.36, .64))
        
        sex <- sample(c("M", "F"), N, replace=TRUE, prob=c(.46, .54))
        
        marital_status <- sample(c("Y", "N"), N, replace=TRUE, 
                                  prob=c(.70, .30))
                                        
        diabetes <- sample(c("Y", "N"), N, replace=TRUE, prob=c(.26, .74))
        
        smoking <- sample(c("Never", "Past", "Current"), N, replace=TRUE, 
                             prob=c(.52, .31, .17))
                             
        VitaminC <- rnorm(N, mean=107, sd=15)

        

        zodiac <- c("Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
                      "Libra","Scorpio", "Sagittarius", "Capricorn","Aquarius", 
                        "Pisces") 
        
        sign <- sample(zodiac, N, replace=TRUE)
        
        simulate_cataract <- function(age, VitaminC){
                logistic <- function(t) 1 / (1 + exp(-t))
                score <- 0.73 +  2^(-1.2)*(age - 72) - 2^(-1.2)*log(VitaminC)  
        
                prob <- logistic(score)
        
                result <- ifelse(runif(length(prob)) < prob, "Y", "N")
        } 
                
        cataract <- simulate_cataract(age, VitaminC)

        data.frame(age, sex, obesity, marital_status, smoking, VitaminC,
                         sign, cataract)
        

}

df <- generate_dataset(2e5)

head(df)

fit <- glm(cataract ~ I(age-72) + log(VitaminC), data=df, family="binomial")
summary(fit)
plot(fit)

fit2 <- glm(cataract ~ age + log(VitaminC) + obesity + marital_status, data=df, family="binomial")
summary(fit2)


```















