---
title: "GaussJordon_Practice"
author: "Xiangyi Xu (Lydia)"
date: "Monday, February 16, 2015"
output:
  html_document:
    keep_md: yes
---

#### Matrix Operation--Practice Matrix Indexing, Identity Matrix

```{r function}
random_invertible_matrix <- function(n, seed=NA){
if (!is.na(seed)){
if(is.character(seed)){
require(digest)
seed <- strtoi(paste0("0x",substr(digest(seed),1,4)))
}
set.seed(seed)
}

# Initialize with a singular matrix
A <- matrix( 1:n^2, nrow=n)

# Choose random integer matrixes until we find a non-singular one
while (det(A) == 0)
A <- matrix( sample(1:99, n^2, replace=T), nrow=n)
A
}
```

```{r matrix}
random_invertible_matrix(3, "jan32.lydia@gmail.com")
n <- 3
A <- random_invertible_matrix(n, "jan32.lydia@gmail.com")
A

# Augment the square matrix by binding an identity matrix on the #right.
Aaug <- cbind(A, diag(n))

# Perform the row operations necessary to complete the Gauss-Jordan elimination.

Aaug[1,] <- Aaug[1,] / Aaug[1,1]
Aaug[2,] <- Aaug[2,] - Aaug[1,] * Aaug[2,1]
Aaug[2,] <- Aaug[2,] / Aaug[2,2]

Aaug[3,] <- Aaug[3,] - Aaug[1,] * Aaug[3,1]
Aaug[3,] <- Aaug[3,] - Aaug[2,] * Aaug[3,2]
Aaug[3,] <- Aaug[3,] / Aaug[3,3]

Aaug[2,] <- Aaug[2,] - Aaug[3,] * Aaug[2,3]
Aaug[1,] <- Aaug[1,] - Aaug[2,] * Aaug[1,2]
Aaug[1,] <- Aaug[1,] - Aaug[3,] * Aaug[1,3]

Ainv <- Aaug[,4:6]
Ainv

# To check using built-in solver
solve(A)

# check by multiplication to get Identity matrix
A %*% Ainv

round(A %*% Ainv,12) # round to 12 decimal places
```
