---
title: "Literate Calculation"
author: "Xiangyi Xu (Lydia)"
date: "Monday, February 02, 2015"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    keep_md: yes
  word_document: default
---

Summary
---------
For pizza lovers, Goat Hill's special combination pizza is very delicious. To get the most for every slice, we will calculate the cost per sqaure inch for each size of pizza. 

Introduction
---------------
Here is detailed information about special combination pizza:

|Size        |Inches  |Price   | 
|------------|:------:|:------:|
|Small       |10"     |$17.95  |
|Medium      |12"     |$21.95  |
|Large       |14"     |$24.95  |
|Extra Large |16"     |$28.95  |

Body
------
An equation for the area of a pizza is:
$$
A = \pi r^2
$$
The diameter of each size pizza is:

```{r pizza_sizes}
d_small   <- 10
d_medium  <- 12
d_large   <- 14
d_exlarge <- 16
```

The price of each size pizza is:

```{r pizza_prices}
p_small   <- 17.95
p_medium  <- 21.95
p_large   <- 24.95
p_exlarge <- 28.95
```

For the small pizza, d=`r d_small` inches:

```{r pizza_area_small}
Area <- function(diameter){
  pi * (diameter/2)^2
}
```

This gives us an area of `r round(Area(d_small), 2)` square inches.

```{r calculate_area}
A_small <- Area(d_small)
```

Therefore, the cost per square inch for small size of pizza is
$`r round((p_small/A_small), 2)`

```{r calculate_price}
V_small <- p_small/A_small
```

And the medium pizza is:
$`r round((p_medium/Area(d_medium)), 2)`
The large pizza is:
$`r round((p_large/Area(d_large)), 2)`
The extra large pizza is:
$`r round((p_exlarge/Area(d_exlarge)), 2)`

As we can see from the graph that, the bigger size the pizza, the cheaper the price is. 

``` {r pizza_plot}
pizza_diameter <- c(small=10, medium=12, large=14, exlarge=16)
pizza_price <- c(small=17.95, medium=21.95, large=24.95, exlarge=28.95)
pizza_area <- Area(pizza_diameter)
price_per_sq_inch <- pizza_price/pizza_area
plot(pizza_diameter, price_per_sq_inch, type="b")
```

Conclusion
------------
Through calculation, we can tell that the extra large pizza is the best deal among the four sizes of pizza. 